### ISSUE TITLE
 FeatureTerminatoR for Penguins?

### ISSUE THREAD

**Issue by sfd99** [StatsGary/FeatureTerminatoR#1]
**_Hi Gary,_**

**FeatureTerminatoR** PKG is great!.
works fine 
with the IRIS data in the example page.

I then tried it 
with the Penguins data,
but it does not reduce the number of important cols.

Here's what I tried :
~~~

 PP <- as.data.frame(penguins) %>% na.omit() # CLEANED UP: no Tibble format! no NAs!.

PP %>% class()
[1] "data.frame"

 sum(is.na(PP))
[1] 0   # no NAs in any row of PP now...good!

# y dep var: "species" of Penguins! (col #1).
> rfe_fit <- rfeTerminator(PP, x_cols= 2:8, y_cols=1, alter_df = TRUE, eval_funcs = rfFuncs)

[INFO] Removing features as a result of recursive feature engineering. Expose rfe_reduced_data from returned list using $ selectors.
[IVS SELECTED] Optimal variables are: bill_length_mm
[IVS SELECTED] Optimal variables are: bill_depth_mm
[IVS SELECTED] Optimal variables are: flipper_length_mm
[IVS SELECTED] Optimal variables are: island
[IVS SELECTED] Optimal variables are: body_mass_g
[IVS SELECTED] Optimal variables are: sex
[IVS SELECTED] Optimal variables are: year
~~~

See?.
It still selects ALL input vars
and does not automatically "reduce" the output DF...
it still has all 8 columns, 
like the original DF.

Help Gary!.
What am I missing...?.
(I'm still learning, so pls keep it simple...).

_thanks!._
**SFd99
San Francisco
latest Rstudio , R 4.1.1, 
Ubuntu Linux**
**FeatureTerminatoR PKG version 1.0.0**

**Comment by StatsGary** [comment]
That means that the features you have are all important and the mean decrease in accuracy has highlighted that these features are all needed. The package is working as expected. It will only remove if they really don't have an affect on the predictive power.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: sfd99 ***@***.***>
Sent: Saturday, September 4, 2021 7:11:52 PM
To: StatsGary/FeatureTerminatoR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StatsGary/FeatureTerminatoR] FeatureTerminatoR for Penguins? (#1)


Hi Gary,

FeatureTerminatoR PKG is great!.
works fine
with the IRIS data in the example page.

I then tried it
with the Penguins data,
but it does not reduce the number of important cols.

Here's what I tried :


 PP <- as.data.frame(penguins) %>% na.omit() # CLEANED UP: no Tibble format! no NAs!.

PP %>% class()
[1] "data.frame"

 sum(is.na(PP))
[1] 0   # no NAs in any row of PP now...good!

# y dep var: "species" of Penguins! (col #1).
> rfe_fit <- rfeTerminator(PP, x_cols= 2:8, y_cols=1, alter_df = TRUE, eval_funcs = rfFuncs)

[INFO] Removing features as a result of recursive feature engineering. Expose rfe_reduced_data from returned list using $ selectors.
[IVS SELECTED] Optimal variables are: bill_length_mm
[IVS SELECTED] Optimal variables are: bill_depth_mm
[IVS SELECTED] Optimal variables are: flipper_length_mm
[IVS SELECTED] Optimal variables are: island
[IVS SELECTED] Optimal variables are: body_mass_g
[IVS SELECTED] Optimal variables are: sex
[IVS SELECTED] Optimal variables are: year


See?.
It still selects ALL input vars
and does not automatically "reduce" the output DF...
it still has all 8 columns,
like the original DF.

Help Gary!.
What am I missing...?.
(I'm still learning, so pls keep it simple...).

thanks!.
SFd99
San Francisco
latest Rstudio , R 4.1.1,
Ubuntu Linux

**Comment by sfd99** [comment]
Thanks 
for the quick answer, Gary.

I see...

I thought it might have been that
some of the Penguin indep x= vars,
(ie:  Island, Sex, Year) 
are Factors - not numeric.

So, 
I'm glad to hear that 
_input Factor vars are not a problem,_
(having both Numeric and Factors 
as x=input vars is OK...). 
Good!.

I'm surprised that it considers
the input var "**year**" ( a Factor),
as important to determine the Penguin "species" y=var!...

I'm still a little confused there...

Thanks for your teacher-patience 
with me...hope you can clear up my doubt.

**SFd99
San Francisco
latest Rstudio , R 4.1.1,
Ubuntu Linux
FeatureTerminatoR PKG version 1.0.0**

**Comment by StatsGary** [comment]
I would look at the variable importance in your data and see which independent variables are significant. However, I am confident that these all play a part on the prediction. However, I don't know the Penguin dataset.

Please use VarImp from the caret package to look at this or similar in TidyModels.

Thanks Gary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
